
/* -- CLEAR EXISTING TABLES FROM DB -- */
DROP TABLE IF EXISTS Images;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Observations;
DROP TYPE IF EXISTS banded_status;
DROP TABLE IF EXISTS Birds;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Users;
/* ----------------------------------- */

/* -- INITIALIZE TABLES AND DATA TYPES -- */
CREATE TABLE Users (
    id SERIAL PRIMARY KEY,
    realname VARCHAR(32),
    username VARCHAR(16) UNIQUE NOT NULL,
    psswrdhash TEXT NOT NULL,
    admin_status BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE Locations (
    id SERIAL PRIMARY KEY,
    muni TEXT UNIQUE NOT NULL,
    prov TEXT,
    country TEXT NOT NULL
);

CREATE TABLE Birds (
    id SERIAL PRIMARY KEY,
    sci TEXT UNIQUE NOT NULL,
    fi TEXT UNIQUE NOT NULL,
    sv TEXT UNIQUE,
    en TEXT UNIQUE
);

CREATE TYPE banded_status AS ENUM ('true', 'false', 'not_known');

CREATE TABLE Observations (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES Users (id),
    location_id INTEGER NOT NULL REFERENCES Locations (id),
    bird_id INTEGER NOT NULL REFERENCES Birds (id),
    bird_count INTEGER NOT NULL,
    observation_date DATE NOT NULL,
    banded banded_status NOT NULL DEFAULT 'not_known',
    band_serial TEXT
);

CREATE TABLE Comments (
    id SERIAL PRIMARY KEY,
    observation_id INTEGER NOT NULL REFERENCES Observations (id),
    user_id INTEGER NOT NULL REFERENCES Users (id),
    content TEXT NOT NULL,
    posting_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(0)
);

CREATE TABLE Images (
    id SERIAL PRIMARY KEY,
    observation_id INTEGER NOT NULL REFERENCES Observations (id),
    user_id INTEGER NOT NULL REFERENCES Users (id),
    imagename TEXT NOT NULL,
    binarydata BYTEA NOT NULL
);
/* -------------------------------------- */

/* -- POPULATE LOCATIONS TABLE WITH MUNICIPALITIES OF FINLAND -- */
INSERT INTO locations (muni,prov,country) VALUES ('Askola','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Espoo','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hanko','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Helsinki','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vantaa','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hyvinkää','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Inkoo','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Järvenpää','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Karkkila','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kauniainen','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kerava','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kirkkonummi','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lapinjärvi','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Loviisa','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lohja','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Myrskylä','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Mäntsälä','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Nurmijärvi','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pornainen','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pukkila','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Porvoo','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Raasepori','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sipoo','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Siuntio','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tuusula','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vihti','Uusimaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Aura','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kaarina','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Koski Tl','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kustavi','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kemiönsaari','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Laitila','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lieto','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Loimaa','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Parainen','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Marttila','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Masku','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Mynämäki','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Naantali','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Nousiainen','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Oripää','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Paimio','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pyhäranta','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pöytyä','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Raisio','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rusko','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Salo','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sauvo','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Somero','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Taivassalo','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Turku','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Uusikaupunki','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vehmaa','Varsinais-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Eura','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Eurajoki','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Harjavalta','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Huittinen','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Jämijärvi','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kankaanpää','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Karvia','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kokemäki','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Merikarvia','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Nakkila','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pomarkku','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pori','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rauma','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Siikainen','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Säkylä','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ulvila','Satakunta','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Forssa','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hattula','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hausjärvi','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Humppila','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hämeenlinna','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Janakkala','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Jokioinen','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Loppi','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Riihimäki','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tammela','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ypäjä','Kanta-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Akaa','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hämeenkyrö','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ikaalinen','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Juupajoki','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kangasala','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kihniö','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kuhmoinen','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lempäälä','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Mänttä-Vilppula','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Nokia','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Orivesi','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Parkano','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pirkkala','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Punkalaidun','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pälkäne','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ruovesi','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sastamala','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tampere','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Urjala','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Valkeakoski','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vesilahti','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Virrat','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ylöjärvi','Pirkanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Asikkala','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hartola','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hollola','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Heinola','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Iitti','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kärkölä','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lahti','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Orimattila','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Padasjoki','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sysmä','Päijät-Häme','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hamina','Kymenlaakso','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kotka','Kymenlaakso','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kouvola','Kymenlaakso','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Miehikkälä','Kymenlaakso','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pyhtää','Kymenlaakso','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Virolahti','Kymenlaakso','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Imatra','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lappeenranta','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lemi','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Luumäki','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Parikkala','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rautjärvi','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ruokolahti','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Savitaipale','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Taipalsaari','Etelä-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Enonkoski','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hirvensalmi','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Juva','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kangasniemi','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Mikkeli','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Mäntyharju','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pertunmaa','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pieksämäki','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Puumala','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rantasalmi','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Savonlinna','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sulkava','Etelä-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Iisalmi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Joroinen','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kaavi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Keitele','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kiuruvesi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kuopio','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lapinlahti','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Leppävirta','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pielavesi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rautalampi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rautavaara','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Siilinjärvi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sonkajärvi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Suonenjoki','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tervo','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tuusniemi','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Varkaus','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vesanto','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vieremä','Pohjois-Savo','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Heinävesi','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ilomantsi','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Joensuu','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Juuka','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kitee','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kontiolahti','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Outokumpu','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lieksa','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Liperi','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Nurmes','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Polvijärvi','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rääkkylä','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tohmajärvi','Pohjois-Karjala','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hankasalmi','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Joutsa','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Jyväskylä','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Jämsä','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kannonkoski','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Karstula','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Keuruu','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kinnula','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kivijärvi','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Konnevesi','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kyyjärvi','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Laukaa','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Luhanka','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Multia','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Muurame','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Petäjävesi','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pihtipudas','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Saarijärvi','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Toivakka','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Uurainen','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Viitasaari','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Äänekoski','Keski-Suomi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Alajärvi','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Alavus','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Evijärvi','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ilmajoki','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Isojoki','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Isokyrö','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Karijoki','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kauhajoki','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kauhava','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kuortane','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kurikka','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lappajärvi','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lapua','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Seinäjoki','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Soini','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Teuva','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vimpeli','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ähtäri','Etelä-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kaskinen','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Korsnäs','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kristiinankaupunki','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kruunupyy','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Laihia','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Luoto','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Maalahti','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Mustasaari','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Närpiö','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pietarsaari','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pedersören kunta','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Uusikaarlepyy','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vaasa','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vöyri','Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Halsua','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kannus','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kaustinen','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kokkola','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lestijärvi','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Perho','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Toholampi','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Veteli','Keski-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Alavieska','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Haapajärvi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Haapavesi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hailuoto','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ii','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kalajoki','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kempele','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kuusamo','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kärsämäki','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Liminka','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lumijoki','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Merijärvi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Muhos','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Nivala','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Oulainen','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Oulu','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pudasjärvi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pyhäjoki','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pyhäjärvi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pyhäntä','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Raahe','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Reisjärvi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sievi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Siikajoki','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vaala','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Siikalatva','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Taivalkoski','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tyrnävä','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Utajärvi','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ylivieska','Pohjois-Pohjanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hyrynsalmi','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kajaani','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kuhmo','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Paltamo','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Puolanka','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ristijärvi','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sotkamo','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Suomussalmi','Kainuu','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Enontekiö','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Inari','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kemi','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Keminmaa','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kittilä','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kolari','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kemijärvi','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Muonio','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pelkosenniemi','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Posio','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ranua','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Rovaniemi','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Salla','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Savukoski','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Simo','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sodankylä','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tervola','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Tornio','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Pello','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Utsjoki','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Ylitornio','Lappi','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Brändö','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Eckerö','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Finström','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Föglö','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Geta','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Hammarland','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Jomala','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kumlinge','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Kökar','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lemland','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Lumparland','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Maarianhamina','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Saltvik','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sottunga','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Sund','Ahvenanmaa','Finland');
INSERT INTO locations (muni,prov,country) VALUES ('Vårdö','Ahvenanmaa','Finland');
/* ------------------------------------------------------------- */

/* -- POPULATE BIRDS TABLE WITH BIRDS OF FINLAND -- */
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phylloscopus trochilus','Pajulintu','Lövsångare','Willow Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Turdus iliacus','Punakylkirastas','Rödvingetrast','Redwing');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Motacilla alba','Västäräkki','Sädesärla','White Wagtail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Corvus corax','Korppi','Korp','Raven');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Turdus pilaris','Räkättirastas','Björktrast','Fieldfare');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Cuculus canorus','Käki','Gök','Cuckoo');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phoenicurus phoenicurus','Leppälintu','Rödstjärt','Redstart');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Turdus philomelos','Laulurastas','Taltrast','Song Thrush');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis spinus','Vihervarpunen','Grönsiska','Siskin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Muscicapa striata','Harmaasieppo','Grå flugsnappare','Spotted Flycatcher');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Bucephala clangula','Telkkä','Knipa','Goldeneye');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Corvus corone','Varis','Kråka','Hooded Crow');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus major','Talitiainen','Talgoxe','Great Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Ficedula hypoleuca','Kirjosieppo','Svartvit flugsnappare','Pied Flycatcher');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anthus trivialis','Metsäkirvinen','Trädpiplärka','Tree Pipit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Emberiza schoeniclus','Pajusirkku','Sävsparv','Reed Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Actitis hypoleucos','Rantasipi','Drillsnäppa','Common Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Fringilla coelebs','Peippo','Bofink','Chaffinch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Dendrocopos major','Käpytikka','Större hackspett','Great Spotted Woodpecker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas crecca','Tavi','Kricka','Teal');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Larus canus','Kalalokki','Fiskmås','Common Gull');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus montanus','Hömötiainen','Talltita','Willow Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Gallinago gallinago','Taivaanvuohi','Enkelbeckasin','Snipe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tetrao tetrix','Teeri','Orre','Black Grouse');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Erithacus rubecula','Punarinta','Rödhake','Robin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas platyrhynchos','Sinisorsa','Gräsand','Mallard');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Hirundo rustica','Haarapääsky','Ladusvala','Swallow');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Turdus viscivorus','Kulorastas','Dubbeltrast','Mistle Thrush');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Cygnus cygnus','Laulujoutsen','Sångsvan','Whooper Swan');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Delichon urbicum','Räystäspääsky','Hussvala','House Martin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Grus grus','Kurki','Trana','Crane');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis chloris','Viherpeippo','Grönfink','Greenfinch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Pica pica','Harakka','Skata','Magpie');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anthus pratensis','Niittykirvinen','Ängspiplärka','Meadow Pipit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Columba palumbus','Sepelkyyhky','Ringduva','Wood Pigeon');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Saxicola rubetra','Pensastasku','Buskskvätta','Whinchat');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Emberiza citrinella','Keltasirkku','Gulsparv','Yellowhammer');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Pyrrhula pyrrhula','Punatulkku','Domherre','Bullfinch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Loxia curvirostra','Pikkukäpylintu','Mindre korsnäbb','Crossbill');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tetrao urogallus','Metso','Tjäder','Capercaillie');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Regulus regulus','Hippiäinen','Kungsfågel','Goldcrest');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Apus apus','Tervapääsky','Tornseglare','Swift');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Prunella modularis','Rautiainen','Järnsparv','Dunnock');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tringa ochropus','Metsäviklo','Skogssnäppa','Green Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus caeruleus','Sinitiainen','Blåmes','Blue Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sylvia borin','Lehtokerttu','Trädgårdssångare','Garden Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Dryocopus martius','Palokärki','Spillkråka','Black Woodpecker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Bonasa bonasia','Pyy','Järpe','Hazel Grouse');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Falco tinnunculus','Tuulihaukka','Tornfalk','Kestrel');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sylvia curruca','Hernekerttu','Ärtsångare','Lesser Whitethroat');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Scolopax rusticola','Lehtokurppa','Morkulla','Woodcock');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Garrulus glandarius','Närhi','Nötskrika','Jay');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Numenius arquata','Kuovi','Storspov','Curlew');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Turdus merula','Mustarastas','Koltrast','Blackbird');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tringa glareola','Liro','Grönbena','Wood Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sterna hirundo','Kalatiira','Fisktärna','Common Tern');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Motacilla flava','Keltavästäräkki','Gulärla','Yellow Wagtail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Larus ridibundus','Naurulokki','Skrattmås','Black-headed Gull');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carpodacus erythrinus','Punavarpunen','Rosenfink','Scarlet Rosefinch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Oenanthe oenanthe','Kivitasku','Stenskvätta','Wheatear');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Larus argentatus','Harmaalokki','Gråtrut','Herring Gull');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phylloscopus collybita','Tiltaltti','Gransångare','Chiffchaff');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Acrocephalus schoenobaenus','Ruokokerttunen','Sävsångare','Sedge Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas penelope','Haapana','Bläsand','Wigeon');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tringa nebularia','Valkoviklo','Gluttsnäppa','Greenshank');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus cristatus','Töyhtötiainen','Tofsmes','Crested Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Certhia familiaris','Puukiipijä','Trädkrypare','Treecreeper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Vanellus vanellus','Töyhtöhyyppä','Tofsvipa','Lapwing');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Gavia arctica','Kuikka','Storlom','Black-throated Diver');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aythya fuligula','Tukkasotka','Vigg','Tufted Duck');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Accipiter nisus','Varpushaukka','Sparvhök','Sparrowhawk');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Passer domesticus','Varpunen','Gråsparv','House Sparrow');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Accipiter gentilis','Kanahaukka','Duvhök','Goshawk');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sylvia communis','Pensaskerttu','Törnsångare','Whitethroat');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Fringilla montifringilla','Järripeippo','Bergfink','Brambling');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phylloscopus sibilatrix','Sirittäjä','Grönsångare','Wood Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Mergus merganser','Isokoskelo','Storskrake','Goosander');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Falco subbuteo','Nuolihaukka','Lärkfalk','Hobby');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Buteo buteo','Hiirihaukka','Ormvråk','Buzzard');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Troglodytes troglodytes','Peukaloinen','Gärdsmyg','Wren');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Alauda arvensis','Kiuru','Sånglärka','Skylark');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis flammea','Urpiainen','Gråsiska','Redpoll');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aegolius funereus','Helmipöllö','Pärluggla','Tengmalm''s Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Lanius collurio','Pikkulepinkäinen','Törnskata','Red-backed Shrike');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Pandion haliaetus','Sääksi','Fiskgjuse','Osprey');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Jynx torquilla','Käenpiika','Göktyta','Wryneck');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sturnus vulgaris','Kottarainen','Stare','Starling');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Mergus serrator','Tukkakoskelo','Småskrake','Red-breasted Merganser');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Riparia riparia','Törmäpääsky','Backsvala','Sand Martin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Larus fuscus','Selkälokki','Silltrut','Lesser Black-backed Gull');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Bombycilla garrulus','Tilhi','Sidensvans','Waxwing');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Corvus monedula','Naakka','Kaja','Jackdaw');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus ater','Kuusitiainen','Svartmes','Coal Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Strix uralensis','Viirupöllö','Slaguggla','Ural Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Pluvialis apricaria','Kapustarinta','Ljungpipare','Golden Plover');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Pernis apivorus','Mehiläishaukka','Bivråk','Honey Buzzard');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Hydrocoloeus minutus','Pikkulokki','Dvärgmås','Little Gull');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Numenius phaeopus','Pikkukuovi','Småspov','Whimbrel');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sylvia atricapilla','Mustapääkerttu','Svarthätta','Blackcap');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Lagopus lagopus','Riekko','Dalripa','Willow Grouse');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Loxia pytyopsittacus','Isokäpylintu','Större korsnäbb','Parrot Crossbill');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Crex crex','Ruisrääkkä','Kornknarr','Corncrake');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Picoides tridactylus','Pohjantikka','Tretåig hackspett','Three-toed Woodpecker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Acrocephalus dumetorum','Viitakerttunen','Busksångare','Blyth''s Reed Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Lanius excubitor','Isolepinkäinen','Varfågel','Great Grey Shrike');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Dendrocopos minor','Pikkutikka','Mindre hackspett','Lesser Spotted Woodpecker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Podiceps cristatus','Silkkiuikku','Skäggdopping','Great Crested Grebe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Glaucidium passerinum','Varpuspöllö','Sparvuggla','Pygmy Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Bubo bubo','Huuhkaja','Berguv','Eagle Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Asio otus','Sarvipöllö','Hornuggla','Long-eared Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Circus cyaneus','Sinisuohaukka','Blå kärrhök','Hen Harrier');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Passer montanus','Pikkuvarpunen','Pilfink','Tree Sparrow');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Luscinia luscinia','Satakieli','Näktergal','Thrush Nightingale');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Emberiza rustica','Pohjansirkku','Videsparv','Rustic Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Falco columbarius','Ampuhaukka','Stenfalk','Merlin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Asio flammeus','Suopöllö','Jorduggla','Short-eared Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Perisoreus infaustus','Kuukkeli','Lavskrika','Siberian Jay');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Podiceps grisegena','Härkälintu','Gråhakedopping','Red-necked Grebe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aegithalos caudatus','Pyrstötiainen','Stjärtmes','Long-tailed Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Circus aeruginosus','Ruskosuohaukka','Brun kärrhök','Marsh Harrier');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sterna paradisaea','Lapintiira','Silvertärna','Arctic Tern');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas acuta','Jouhisorsa','Stjärtand','Pintail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Gavia stellata','Kaakkuri','Smålom','Red-throated Diver');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas clypeata','Lapasorsa','Skedand','Shoveler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phasianus colchicus','Fasaani','Fasan','Pheasant');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Hippolais icterina','Kultarinta','Härmsångare','Icterine Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Picus canus','Harmaapäätikka','Gråspett','Grey-headed Woodpecker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Locustella naevia','Pensassirkkalintu','Gräshoppsångare','Grasshopper Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Charadrius dubius','Pikkutylli','Mindre strandpipare','Little Ringed Plover');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Acrocephalus palustris','Luhtakerttunen','Kärrsångare','Marsh Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tringa totanus','Punajalkaviklo','Rödbena','Redshank');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Fulica atra','Nokikana','Sothöna','Coot');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phylloscopus trochiloides','Idänuunilintu','Lundsångare','Greenish Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Emberiza hortulana','Peltosirkku','Ortolansparv','Ortolan Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Branta canadensis','Kanadanhanhi','Kanadagås','Canada Goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Botaurus stellaris','Kaulushaikara','Rördrom','Bittern');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Ficedula parva','Pikkusieppo','Mindre flugsnappare','Red-breasted Flycatcher');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Podiceps auritus','Mustakurkku-uikku','Svarthakedopping','Slavonian Grebe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis cannabina','Hemppo','Hämpling','Linnet');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aquila chrysaetos','Maakotka','Kungsörn','Golden Eagle');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Mergellus albellus','Uivelo','Salskrake','Smew');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Strix aluco','Lehtopöllö','Kattuggla','Tawny Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Buteo lagopus','Piekana','Fjällvråk','Rough-legged Buzzard');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Columba oenas','Uuttukyyhky','Skogsduva','Stock Dove');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anser fabalis','Metsähanhi','Sädgås','Bean Goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Caprimulgus europaeus','Kehrääjä','Nattskärra','Nightjar');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Columba livia','Kesykyyhky','Tamduva','Rock Dove');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Haliaeetus albicilla','Merikotka','Havsörn','White-tailed Eagle');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus cinctus','Lapintiainen','Lappmes','Siberian Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Haematopus ostralegus','Meriharakka','Strandskata','Oystercatcher');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tringa erythropus','Mustaviklo','Svartsnäppa','Spotted Redshank');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Charadrius hiaticula','Tylli','Större strandpipare','Ringed Plover');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Locustella fluviatilis','Viitasirkkalintu','Flodsångare','River Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Surnia ulula','Hiiripöllö','Hökuggla','Hawk Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis carduelis','Tikli','Steglits','Goldfinch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aythya ferina','Punasotka','Brunand','Pochard');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Porzana porzana','Luhtahuitti','Småfläckig sumphöna','Spotted Crake');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Philomachus pugnax','Suokukko','Brushane','Ruff');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Larus marinus','Merilokki','Havstrut','Great Black-backed Gull');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Luscinia svecica','Sinirinta','Blåhake','Bluethroat');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Lullula arborea','Kangaskiuru','Trädlärka','Woodlark');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Cygnus olor','Kyhmyjoutsen','Knölsvan','Mute Swan');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Ardea cinerea','Harmaahaikara','Häger','Grey Heron');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Acrocephalus scirpaceus','Rytikerttunen','Rörsångare','Reed Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas querquedula','Heinätavi','Årta','Garganey');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Oriolus oriolus','Kuhankeittäjä','Sommargylling','Golden Oriole');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Melanitta fusca','Pilkkasiipi','Svärta','Velvet Scoter');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Perdix perdix','Peltopyy','Rapphöna','Partridge');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anser anser','Merihanhi','Grågås','Greylag Goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Lymnocryptes minimus','Jänkäkurppa','Dvärgbeckasin','Jack Snipe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Rallus aquaticus','Luhtakana','Vattenrall','Water Rail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Falco peregrinus','Muuttohaukka','Pilgrimsfalk','Peregrine');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Strix nebulosa','Lapinpöllö','Lappuggla','Great Grey Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Dendrocopos leucotos','Valkoselkätikka','Vitryggig hackspett','White-backed Woodpecker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Coturnix coturnix','Viiriäinen','Vaktel','Quail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anas strepera','Harmaasorsa','Snatterand','Gadwall');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Somateria mollissima','Haahka','Ejder','Eider');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Nucifraga caryocatactes','Pähkinähakki','Nötkråka','Nutcracker');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Pinicola enucleator','Taviokuurna','Tallbit','Pine Grosbeak');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Melanitta nigra','Mustalintu','Sjöorre','Common Scoter');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Arenaria interpres','Karikukko','Roskarl','Turnstone');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Limicola falcinellus','Jänkäsirriäinen','Myrsnäppa','Broad-billed Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Branta leucopsis','Valkoposkihanhi','Vitkindad gås','Barnacle Goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phalacrocorax carbo','Merimetso','Storskarv','Great Cormorant');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phalaropus lobatus','Vesipääsky','Smalnäbbad simsnäppa','Red-necked Phalarope');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Stercorarius parasiticus','Merikihu','Labb','Arctic Skua');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Cepphus grylle','Riskilä','Tobisgrissla','Black Guillemot');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Coccothraustes coccothraustes','Nokkavarpunen','Stenknäck','Hawfinch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Hydroprogne caspia','Räyskä','Skräntärna','Caspian Tern');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Acrocephalus arundinaceus','Rastaskerttunen','Trastsångare','Great Reed Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Loxia leucoptera','Kirjosiipikäpylintu','Bändelkorsnäbb','Two-barred Crossbill');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Cinclus cinclus','Koskikara','Strömstare','Dipper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Streptopelia decaocto','Turkinkyyhky','Turkduva','Collared Dove');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Calcarius lapponicus','Lapinsirkku','Lappsparv','Lapland Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anthus petrosus','Luotokirvinen','Skärpiplärka','Water Pipit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tarsiger cyanurus','Sinipyrstö','Blåstjärt','Red-flanked Bluetail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Emberiza pusilla','Pikkusirkku','Dvärgsparv','Little Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Alca torda','Ruokki','Tordmule','Razorbill');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Calidris temminckii','Lapinsirri','Mosnäppa','Temminck''s Stint');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Stercorarius longicaudus','Tunturikihu','Fjällabb','Long-tailed Skua');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Clangula hyemalis','Alli','Alfågel','Long-tailed Duck');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tadorna tadorna','Ristisorsa','Gravand','Shelduck');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aythya marila','Lapasotka','Bergand','Scaup');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Gallinula chloropus','Liejukana','Rörhöna','Moorhen');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phoenicurus ochruros','Mustaleppälintu','Svart rödstjärt','Black Redstart');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Calidris alpina','Suosirri','Kärrsnäppa','Dunlin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Lagopus muta','Kiiruna','Fjällripa','Ptarmigan');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Corvus frugilegus','Mustavaris','Råka','Rook');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Limosa lapponica','Punakuiri','Myrspov','Bar-tailed Godwit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Panurus biarmicus','Viiksitimali','Skäggmes','Bearded Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Phylloscopus borealis','Lapinuunilintu','Nordsångare','Arctic Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Plectrophenax nivalis','Pulmunen','Snösparv','Snow Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Falco rusticolus','Tunturihaukka','Jaktfalk','Gyrfalcon');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis hornemanni','Tundraurpiainen','Snösiska','Arctic Redpoll');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Motacilla cinerea','Virtavästäräkki','Forsärla','Grey Wagtail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Milvus migrans','Haarahaukka','Brunglada','Black Kite');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Charadrius morinellus','Keräkurmitsa','Fjällpipare','Dotterel');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sylvia nisoria','Kirjokerttu','Höksångare','Barred Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Limosa limosa','Mustapyrstökuiri','Rödspov','Black-tailed Godwit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anthus cervinus','Lapinkirvinen','Rödstrupig piplärka','Red-throated Pipit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Chlidonias niger','Mustatiira','Svarttärna','Black Tern');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sternula albifrons','Pikkutiira','Småtärna','Little Tern');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Locustella luscinioides','Ruokosirkkalintu','Vassångare','Savi''s Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Sitta europaea','Pähkinänakkeli','Nötväcka','Nuthatch');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Circus pygargus','Niittysuohaukka','Ängshök','Montagu''s Harrier');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Hippolais caligata','Pikkukultarinta','Stäppsångare','Booted Warbler');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Streptopelia turtur','Turturikyyhky','Turturduva','Turtle Dove');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Turdus torquatus','Sepelrastas','Ringtrast','Ring Ouzel');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Motacilla citreola','Sitruunavästäräkki','Citronärla','Citrine Wagtail');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Gallinago media','Heinäkurppa','Dubbelbeckasin','Great Snipe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Alcedo atthis','Kuningaskalastaja','Kungsfiskare','Kingfisher');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tachybaptus ruficollis','Pikku-uikku','Smådopping','Little Grebe');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Tringa stagnatilis','Lampiviklo','Dammsnäppa','Marsh Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Uria aalge','Etelänkiisla','Sillgrissla','Guillemot');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Circus macrourus','Arosuohaukka','Stäpphök','Pallid Harrier');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Porzana parva','Pikkuhuitti','Mindre sumphöna','Little Crake');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Serinus serinus','Keltahemppo','Gulhämpling','Serin');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Falco vespertinus','Punajalkahaukka','Aftonfalk','Red-footed Falcon');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Xenus cinereus','Rantakurvi','Tereksnäppa','Terek Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Remiz pendulinus','Pussitiainen','Pungmes','Penduline Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Bubo scandiacus','Tunturipöllö','Fjälluggla','Snowy Owl');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Carduelis flavirostris','Vuorihemppo','Vinterhämpling','Twite');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Calidris maritima','Merisirri','Skärsnäppa','Purple Sandpiper');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Eremophila alpestris','Tunturikiuru','Berglärka','Shore Lark');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anser indicus','Tiibetinhanhi','Stripgås','Bar-headed goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Parus cyanus','Valkopäätiainen','Azurmes','Azure Tit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Saxicola torquatus','Mustapäätasku','Svarthakad buskskvätta','Stonechat');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Aquila clanga','Kiljukotka','Större skrikörn','Spotted Eagle');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Emberiza aureola','Kultasirkku','Gyllensparv','Yellow-breasted Bunting');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anser caerulescens','Lumihanhi','Snögås','Snow Goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anthus campestris','Nummikirvinen','Fältpiplärka','Tawny Pipit');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Anser erythropus','Kiljuhanhi','Fjällgås','Lesser White-fronted Goose');
INSERT INTO birds (sci,fi,sv,en) VALUES ('Calidris minuta','Pikkusirri','Småsnäppa','Little Stint');
/* ------------------------------------------------ */